# -*- coding: utf-8 -*-
"""Taiyo web scraping assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xbp7-HFI7mxkx0v5RF1S4WiAJFenXU30
"""

## Taiyo web scraping assignment
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

!pip install requests
!pip install html5lib
!pip install bs4

import urllib.request
import pandas as pd
url = "https://developer.taiyo.ai/api-doc/ProjectsandTenders/"

with urllib.request.urlopen(url) as i:
    html = i.read()
    
data = pd.read_html(html)[0]
print(data.head())

data=data.to_csv("ProjectsandTenders.csv")

data=pd.read_csv("/content/ProjectsandTenders.csv")
data

data.columns

data.head(10)

# EDA
data.head(10)

data.shape

data.isna().sum()

data.dropna(axis=0, inplace=True)

data.isna().sum()

data.shape

data.head()

