# -*- coding: utf-8 -*-
"""scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OUTuxwRw-9QiarOTmXq_10tiSt-0JoTV
"""

import requests, csv
from bs4 import BeautifulSoup

r = requests.get("https://www.census.gov/data.html")
html_doc = r.text
soup = BeautifulSoup(html_doc, 'html.parser')
print(soup.prettify())

links = soup.find_all("a", href = True)
print(links)

links=[]
for link in links:
  hrefs = link.get('href')
  if hrefs.startswith('/'):
        links.append('https://www.census.gov' + hrefs)
  else:
      links.append(hrefs)

with open('links.csv', 'w') as f:
    writer = csv.writer(f)
    for link in links:
        writer.writerow([link])
    f.close()

